### ISSUE TITLE
Unable to initialize parse

### ISSUE THREAD

**Issue by justkawal** [AdvancedProjects/Parse-SDK-Dart#2]
Any help would be beneficial

I am trying to use parse locally by running dart file.

main.dart
```dart
void main(List<String> args) async {
  await Parse().initialize(
    'my-parse-keys-here ',
    'my / parse link here //',
    debug: true,
  );
/*
Some shelf dart code here
*/
}
```

pubspec.yaml
```yaml
name: server
description: A web server built using the shelf package.
# version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  shelf: ^0.7.9
  pointycastle:
  asn1lib:
  parse_server_sdk:
    git:
      url: https://github.com/AdvancedProjects/Parse-SDK-Dart.git
  uuid:

dev_dependencies:
  pedantic: ^1.9.0
```

Exception:
```
Unhandled exception:
FileSystemException: Creation failed, path = '/parse' (OS Error: Read-only file system, errno = 30)
#0      _wrap.<anonymous closure> (package:sembast/src/io/file_system_io.dart:103:7)
#1      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#5      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
